AppBlog/urls.py
from django.urls import path, re_path
from .views import *
from .views import DetailMs, CanalDetailView, mensajes_privados, ListarUser,  Inbox
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView


UUID_CANAL_REGEX = r'canal/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'



urlpatterns = [
    
    path('', inicio, name="inicio"),
    path("leerTemas/", leerTemas, name="leerTemas"),
    path("leerTemas2/<id>", leerTemas2, name="leerTemas2"),
    path("agregarTema/", agregarTema, name="agregarTema"),
    path("editarTema/<id>", editarTema, name="editarTema"),
    path("eliminarTema/<id>", eliminarTema, name="eliminarTema"),
    path("buscar/", buscar, name="buscar"),
    path("temaBusq/", temaBusq, name="temaBusq"),

    path("register/", register, name="register"),
    path("login/", loginvista, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("editarPerfil/", editarPerfil, name="editarPerfil"),
    path("verPerfil/", verPerfil, name="verPerfil"),
    path("acerca/", acerca, name="acerca"),
    path("ListarUser/", ListarUser, name="ListarUser"),
    path("agregarAvatar/", agregarAvatar, name="agregarAvatar"),
    path("agregarImagen/", agregarImagen, name="agregarImagen"),
    path("agregarExtra/", agregarExtra, name="agregarExtra"),


    




    
    
    re_path(UUID_CANAL_REGEX, CanalDetailView.as_view()),
    path("dm/<str:username>", mensajes_privados),
    path("ms/<str:username>", DetailMs.as_view(), name="detailms"),
    path('Inbox', Inbox.as_view(), name="Inbox"),
    
    
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from AppBlog.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppBlog/', include("AppBlog.urls")),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AppBlog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.conf import settings
from django.db.models import Count
from django.db import models
from django.apps import apps
import uuid


User = settings.AUTH_USER_MODEL

# Create your models here.

# Modelo Tema
class Tema(models.Model):
    titulo= models.CharField(max_length=50)
    subtitulo= models.CharField(max_length=50)
    fecha= models.DateField(auto_now_add=True)
    autor= models.CharField(max_length=50)
    resumen= models.CharField(max_length=50)
    cuerpo= models.CharField(max_length=200)
    img_tema= models.ImageField(null=True, blank=True, upload_to="img")
    

    def __str__(self):
        return f"{self.titulo} - {self.subtitulo} - {self.fecha} - {self.resumen} - {self.autor} - {self.cuerpo} "

#modelo Avatar
class Avatar(models.Model):
    imagen= models.ImageField(upload_to="avatars", null=True, blank = True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} - {self.imagen}"



class Extra(models.Model):
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=200)
    pagina = models.URLField(max_length = 200)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    
    def __str__(self):
        return f"{self.user} - {self.direccion} - {self.telefono} - {self.pagina} - {self.user}"




#Modelo displayusername sirve para mostrar nombre de usuario


class ModelBase(models.Model):
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal   = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	texto =  models.TextField()

class CanalUsuario(ModelBase):
	canal  = models.ForeignKey("Canal", null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)


class CanalQuerySet(models.QuerySet):

	def solo_uno(self):
		return self.annotate(num_usuarios=Count("usuarios")).filter(num_usuarios=1)

	def solo_dos(self):
		return self.annotate(num_usuarios= Count("usuarios")).filter(num_usuarios=2)

	def filtrar_por_username(self, username):
		return self.filter(canalusuario__usuario__username=username)


class CanalManager(models.Manager):
	
	def get_queryset(self, *args, **kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self, username_a, username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)

	def obtener_o_crear_canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first, False

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_o_crear_canal_ms(self, username_a, username_b):
		qs = self.filtrar_ms_por_privado(username_a, username_b)
		if qs.exists():

			return qs.order_by("tiempo").first(), False #obj, created

		User = apps.get_model("auth", model_name='User')
		usuario_a, usuario_b = None, None
		try:
			usuario_a = User.objects.get(username=username_a)
		except User.DoesNotExist:
			return None, False

		try:
			usuario_b = User.objects.get(username=username_b)
		except User.DoesNotExist:
			return None, False

		if usuario_a == None or usuario_b==None:
			return None, False

		
		obj_canal =Canal.objects.create()
		canal_usuario_a = CanalUsuario(usuario=usuario_a, canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=usuario_b, canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a, canal_usuario_b])
		return obj_canal, True

class Canal(ModelBase):


	usuarios = models.ManyToManyField(User, blank=True, through=CanalUsuario)

	objects = CanalManager()

class displayusername(models.Model):
    username= models.CharField(max_length=50)

AppBlog/views.py
from django.shortcuts import render

from django.http import HttpResponse, Http404, JsonResponse
from django.core.exceptions import PermissionDenied

from django.urls import reverse_lazy

from .models import *      
from .models import CanalMensaje, CanalUsuario, Canal

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.views.generic.edit import FormMixin

from django.core.exceptions import PermissionDenied


from AppBlog.forms import TemaFormu,  RegistroUsuarioForm, UserEditForm, AvatarForm, ExtraForm, FormMensajes

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.models import User


# Create your views here.

def inicio(request):

    return render (request, "AppBlog/inicio.html", {"avatar": obtenerAvatar(request)})


@login_required
def leerTemas(request):

    temas= Tema.objects.all()

    if temas!='':
        return render(request, "AppBlog/temario.html", {"temas": temas})
    else:
        return render(request, "AppBlog/temario.html", {"temas": temas, "mensaje": "no hay tema vista"})




@login_required
def agregarTema(request):

    if request.method=="POST":

        form=TemaFormu(request.POST, request.FILES)

        if form.is_valid():

            info=form.cleaned_data

            titulo=info["titulo"]

            subtitulo=info["subtitulo"]

            autor=info["autor"]

            resumen=info["resumen"]    

            cuerpo=info["cuerpo"]    

            img_tema=info["img_tema"]  

            tema= Tema(titulo=titulo, subtitulo=subtitulo, autor=autor, resumen=resumen, cuerpo=cuerpo, img_tema=img_tema)

            tema.save()

            temas= Tema.objects.all()

            return render(request, "AppBlog/temario.html", {"temas": temas, "mensaje": "tema guardado correctamente"})       
        else:

            return render(request, "AppBlog/temaFormulario.html", {"form": form, "mensaje": "informacion no valida"})
    else:

        form= TemaFormu()

        return render(request, "AppBlog/temaFormulario.html", {"form": form})



@login_required
def editarTema(request, id):
    tema= Tema.objects.get(id=id)
    if request.method=="POST":
        form=TemaFormu(request.POST)
        if form.is_valid():
            info=form.cleaned_data
            tema.titulo=info["titulo"]
            tema.subtitulo=info["subtitulo"]
            tema.autor=info["autor"]  
            tema.resumen=info["resumen"]
            tema.cuerpo=info["cuerpo"]  
            tema.save()
            temas=Tema.objects.all()                        
            return render(request, "AppBlog/temario.html", {"temas": temas, "mensaje":  "Tema editado correctamente"})
        pass
    else:        
        form= TemaFormu(initial={"titulo":tema.titulo, "subtitulo":tema.subtitulo, "autor":tema.autor, "resumen":tema.resumen, "cuerpo":tema.cuerpo})
        return render(request, "AppBlog/temaEdit.html", {"form": form, "tema": tema})



@login_required
def eliminarTema(request, id):

    tema= Tema.objects.get(id=id)
    tema.delete()

    temas= Tema.objects.all()

    return render(request, "AppBlog/temario.html", {"temas": temas, "mensaje": "tema eliminado correctamente"})      



def temaBusq(request):
    return render(request, "AppBlog/temaBusq.html")



@login_required
def buscar(request):
    titulo= request.GET["titulo"]
    if titulo!="":
        temas= Tema.objects.filter(titulo__contains =titulo)    
        return render(request, "AppBlog/temaBusqResul.html", {"temas": temas})
    else:
        return render(request, "AppBlog/temaBusq.html", {"mensaje": "ingresa un titulo existente"})  








def register(request):
    if request.method=="POST":
        form= RegistroUsuarioForm(request.POST)
        if form.is_valid():
            username= form.cleaned_data.get("username")
            form.save()
            return render(request, "AppBlog/inicio.html" ,{"mensaje":f"Usuario {username} creado correctamente"})    
        else:
            return render(request, "AppBlog/register.html", {"form": form, "mensaje": "Error al crear usuario"})
    else: 
        form= RegistroUsuarioForm()
        return render(request, "AppBlog/register.html", {"form": form})






def loginvista(request):
    if request.method=="POST":
        form=AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            info=form.cleaned_data
            usu=info["username"]
            clave=info["password"]
            usuario=authenticate(username=usu, password=clave)
            if usuario is not None:
                login(request, usuario)
                return render(request, "AppBlog/inicio.html", {"mensaje":f"Usuario {usu} logeado correctamente"})
            else:
                return render(request, "AppBlog/login.html", {"form": form, "mensaje": "Usuario o contraseña incorrecto"})
        else: 
            return render(request, "AppBlog/login.html", {"form": form, "mensaje": "Usuario o contraseña incorrecto"})
    else:
        form=AuthenticationForm()
        return render(request, "AppBlog/login.html", {"form":form})



def editarPerfil(request):
    usuario=request.user

    if request.method=="POST":
        form=UserEditForm(request.POST)
        if form.is_valid():
            info=form.cleaned_data
            usuario.email=info["email"]
            usuario.password1=info["password1"]
            usuario.password2=info["password2"]
            usuario.first_name=info["first_name"]
            usuario.last_name=info["last_name"]
            usuario.save()
            return render(request, "AppBlog/inicio.html", {"mensaje":f"Usuario {usuario.username} editado correctamente"})
        else:
            return render(request, "AppBlog/editarPerfil.html", {"form": form, "nombreusuario":usuario.username})
    else:
        form=UserEditForm(instance=usuario)
        return render(request, "AppBlog/editarPerfil.html", {"form": form, "nombreusuario":usuario.username})


@login_required
def verPerfil(request):
    usuario=request.user
    return render(request, "AppBlog/verPerfil.html", {"usuario":usuario, "avatar": obtenerAvatar(request)})
	



@login_required
def leerTemas2(request, id):
    tema= Tema.objects.get(id=id)
    return render(request, "AppBlog/detalleTema.html", {"tema": tema})

    



def acerca(request):
    return render(request, "AppBlog/acerca.html")



@login_required
def obtenerAvatar(request):
    lista=Avatar.objects.filter(user=request.user) 
    if len(lista)!=0:
        avatar=lista[0].imagen.url
    else:
        avatar="/media/avatars/avatarpordefecto.png"
    return avatar




def ListarUser(request):

    displayusername= User.objects.all()    
    return render(request, "AppBlog/verUsuarios.html", {"displayusername": displayusername})




def agregarAvatar(request):
    if request.method=="POST":
        form=AvatarForm(request.POST, request.FILES)
        if form.is_valid():
            avatar=Avatar(user=request.user, imagen=request.FILES["imagen"])
            avatarViejo=Avatar.objects.filter(user=request.user)
            if len(avatarViejo)>0:
                avatarViejo[0].delete()
            avatar.save()
            return render(request, "AppBlog/inicio.html", {"mensaje":f"Avatar agregado correctamente"})
        else:
            return render(request, "AppBlog/agregarAvatar.html", {"form": form, "usuario": request.user, "mensaje":"Error al agregar el avatar"})
    else:
        form=AvatarForm()
        return render(request, "AppBlog/agregarAvatar.html", {"form": form, "usuario": request.user})



def agregarImagen(request):
    if request.method=="POST":
        form=ImagenTemaForm(request.POST, request.FILES)
        if form.is_valid():
            imagen=Imagen(imagen=request.FILES["imagen"])
            imagenVieja=Imagen.objects.filter()
            if len(imagenVieja)>0:
                imagenVieja[0].delete()
            imagen.save()
            return render(request, "AppBlog/inicio.html", {"mensaje":f"imagen agregado correctamente"})
        else:
            return render(request, "AppBlog/agregarImagen.html", {"form": form, "mensaje":"Error al agregar el imagen"})
    else:
        form=ImagenTemaForm()
        return render(request, "AppBlog/agregarImagen.html", {"form": form})



def agregarExtra(request):

    if request.method=="POST":

        form=ExtraForm(request.POST)

        if form.is_valid():

            info=form.cleaned_data

            direccion=info["direccion"]

            telefono=info["telefono"] 

            pagina=info["pagina"]             

            extra= Extra(direccion=direccion, telefono=telefono, pagina=pagina)

            extra.save()

            extra= Extra.objects.all()

            return render(request, "AppBlog/verPerfil2.html", {"extra": extra, "mensaje": "datos correctamente"})       
        else:

            return render(request, "AppBlog/agregarExtra.html", {"form": form, "mensaje": "informacion no valida"})
    else:
        form= ExtraForm()
        return render(request, "AppBlog/agregarExtra.html", {"form": form})       





class Inbox(View):
    def get(self, request):

        inbox = Canal.objects.filter(canalusuario__usuario__in=[request.user.id])

        context = {
            
            "inbox":inbox

        }

        return render(request, 'AppBlog/inbox.html', context)



# def inbox(self, request):

#         inbox = Canal.objects.filter(canalusuario__usuario___in=[request.user.id])

#         context = {
            
#             "inbox":inbox

#         }

#         return render(request, "AppBlog/inbox.html", context)


class CanalFormMixin(FormMixin):
	form_class =FormMensajes
	#success_url = "./"

    
	def is_ajax():

AppBlog/templates/AppBlog/abuelo.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Home - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="static/assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />
    </head>
    <body>

        {% block titulo %}

        {% endblock %}

        <!-- Responsive navbar-->
                          
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
            
                    <a class="navbar-brand"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {%if user.is_authenticated %} 
                        <li class="nav-item"><a class="nav-link" href="{% url 'inicio' %}">Bienvenido: {{ user.username }}</a></li>  
                        

                        <li class="nav-item"><a class="nav-link" href="{% url 'inicio' %}">Inicio</a></li>                    
                        <li class="nav-item"><a class="nav-link" href="{% url 'temaBusq' %}">Buscar</a></li> 
                        <li class="nav-item"><a class="nav-link" href="{% url 'Inbox' %}">Inbox</a></li>    
                        
                        
                                        
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'leerTemas' %}">Temario</a></li>
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'verPerfil' %}">Perfil</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'acerca' %}">Acerca de</a></li>
                        <a class="btn btn-danger" href="{% url 'logout' %}">Salir</a>
                        
                        
                        {% else %}
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'inicio' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'register' %}">Registro</a></li>
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'acerca' %}">Acerca de</a></li>
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    {% block titulo_ind %}

                    <h1 class="fw-bolder"></h1>

                    {% endblock %}

                    {% block Subtitulo %}
                    <h1 class="fw-bolder">BIENVENIDOS AL BLOG TECNOLOGICO EJ</h1>
                    
                    {% endblock %}



                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="float-auto container">
            
            {% block contenido_que_cambia %}

                 

            {% endblock %}

        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/js/scripts.js"></script>
    </body>
</html>

AppBlog/templates/AppBlog/acerca.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block contenido_que_cambia %}

   

</head>
<body>
    <title>Blog IT  </title>

    Ingeniero de Sistemas con experiencia  en el área de Soporte Técnico en medianas y grandes empresas, previsor y con capacidad para la 
    identificación de problemas y búsqueda de soluciones de manera eficaz y óptima.

    Con conocimientos avanzados en computación, manejo de sistemas operativos 
    Software Libre (LINUX, Ubuntu) y Microsoft Windows (XP, Vista, 7, 8, 10, 11, Server), Manejo de Base de Datos PostgrSQL y MySQL, 
    redes, configuración de VPN, DCHP, Servidor Apache, Máquinas Virtuales, conocimientos básicos en programación: C/C++, Php, Javascript, manejo de Css3, Html.

    Experiencia en trato directo al público, atención telefónica, soporte técnico presencial o remoto, ofreciendo siempre un excelente servicio al cliente.


</body>


{% endblock %}
</html>

AppBlog/templates/AppBlog/agregarAvatar.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}

{% block titulo %}

{% endblock %}



{% block contenido_que_cambia %}
<h1 class="card-title">Editar Avatar de: {{ usuario.username }} </h1>



<h3>{{ mensaje }}</h3>

<form action="{% url 'agregarAvatar' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}

    <table>

        {{ form.as_table }}
    
    </table>

    <input type="submit" class="btn btn-primary btn-sm" value="Agregar Avatar">


</form>


<h2>{{ mensaje }}</h2>
{% endblock %}

AppBlog/templates/AppBlog/base.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>
		Dm
	</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');

		*{
			margin: 0;
			padding: 0;
		}

		body{
			background:#fafafa;
		}

		h1, h2, h3, p, small{
			font-family: 'Roboto', sans-serif;
		}

		.div_main{
			width: 60%;
			margin: 50px auto;
		}

	</style>
</head>
<body>

	<div class="div_main">
		{% block contenido_que_cambia %}
		
		{% endblock %}
	</div>

</body>
</html>

AppBlog/templates/AppBlog/editarPerfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1 class="mb-5">EDITANDO PERFIL: {{ nombreusuario }} </h1>

    <h3>{{ mensaje }}</h3>
    
    <form action="{% url 'editarPerfil' %}" method="POST"> {% csrf_token %}
    
        <table>
    
            {{ form.as_table }}
        
        </table>
    
        <input type="submit" value="Modificar Cambios">
    
    
    
    
    </form>
    


</body>
</html>

AppBlog/templates/AppBlog/inbox.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}


{% load static %}

{% block contenido_que_cambia %}


<h1>
	Bienvenido {{user}}. Inbox
</h1>

{% for inbox in inbox %}
<div class="div_inbox">

	
	{% for second_user in inbox.canalusuario_set.all %}

		{% if second_user.usuario ==  request.user %}

		{% else %}

			<a href="{% url 'detailms' second_user.usuario.username %}">
				<p>
					{{second_user.usuario}}
				</p>
				<small>
					({{inbox.canalmensaje_set.count}}) Mensajes
				</small>
			</a>

		{% endif %}

	{% endfor %}

	{% if inbox.canalmensaje_set.count != 0 %}
		<div class="div_ms_inbox">
			
			{% with ultimo_mensaje=inbox.canalmensaje_set.last %}

				<p>
					Mensaje: {{ultimo_mensaje.texto}}
				</p>

				<p>
					Usuario: {{ultimo_mensaje.usuario}}
				</p>

			{% endwith %}
		</div>	
	{% else %}
		<p>
			No hay mensajes en nuestro inbox
		</p>
	{% endif %}



</div>
{% empty %}

<h2>
	Inbox Vacio
</h2>

{% endfor %}

<li class="nav-item"><a class="btn btn-primary btn-sm" href="{% url 'ListarUser' %}">Escribe a Otros Usuarios</a></li>  


<style>
	
	.div_inbox{
		width: 90%;
		margin:10px auto;
		background: #fff;
		border-radius: 5px;
		border:1px solid #e6e6e6;
		padding: 5px;
	}

</style>
{% endblock %}

AppBlog/templates/AppBlog/inicio.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}




{% block contenido_que_cambia %}
<h1> </h1>
{% block titulo %}


{% endblock %}

<h2>{{ mensaje }}</h2>
<img src="{{ avatar }}" alt="">





{% block subtitulo %}
<div>
    <p><h1>Bienvenidos al Blog tecnologico del 2013 con la mejor información de la red</p></h1> 
    <p> Por favor elija la opcion de su preferencia.</p>

</div>


{% endblock %}
{% endblock %}

AppBlog/templates/AppBlog/register.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
</head>
<body>




{% block contenido_que_cambia %}

<h2 class="card-title">Registrarse</h2>

<h3>{{ mensaje }}</h3>

<form action="{% url 'register' %}" method="POST"> {% csrf_token %}

    <table>

        {{ form.as_table }}
    
    </table>

    <input type="submit" class="btn btn-primary btn-sm" value="Crear Usuario">




</form>


{% endblock %}
    
</body>
</html>

AppBlog/templates/AppBlog/temaFormulario.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    
    
{% block contenido_que_cambia %}



<h2 class="card-title">Agregar Tema Nuevo</h2>


    <form action="{% url 'agregarTema' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}

        <table>
    
            {{ form.as_table }}
        
        </table>
    
        <input type="submit" class="btn btn-primary btn-sm" value="Guardar Tema">
   
    </form>

<h3>{{ mensaje }}</h3>

{% endblock %}


</body>
</html>

AppBlog/templates/AppBlog/verPerfil2.html
{% extends "AppBlog/abuelo.html" %}

{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>
<body>


    

{% block contenido_que_cambia %}

<h3 class="card-title">Datos extras</h3>





{% if extra %}





<li> {{ extra.direccion }}</li>
<li> {{ extra.telefono }}</li>
<li> {{ extra.pagina }}</li>







{% else %}
<h2>NO HAY Datos</h2>

{% endif %}
{% endblock %}
</body>
</html>